/**
 * Fragment Maker — Single-file bundle
 * https://github.com/dfinity/fragment-maker
 *
 * Generated by: npm run bundle
 * Do not edit manually — modify the source files and re-run the script.
 *
 * Copy this single file to your project for full Fragment Maker support:
 * - Pattern and text SVG generation
 * - Hover animation (React)
 * - Responsive container sizing (React)
 *
 * Usage:
 *   import { generateSvgFromExport, generateDiffSvgFromExport, useFragmentReveal } from './fragment-maker';
 */

import { useCallback, useEffect, useRef, useState } from 'react';

// Types

/** A glyph is a 2D boolean array: rows × columns. true = filled pixel */
export type Glyph = boolean[][];

/** Map of characters to their glyph definitions */
export type GlyphMap = Record<string, Glyph>;

/** Font definition with metadata */
export interface BitmapFont {
  /** Canonical width (columns) */
  width: number;
  /** Canonical height (rows) */
  height: number;
  /** Character to glyph mapping */
  glyphs: GlyphMap;
}

/** Available font sizes */
export type FontSize = '3x5' | '5x7' | '7x9';

/** Font data: all three font sizes with their glyph definitions */
export type FontData = Record<FontSize, BitmapFont>;

/** Result of font selection */
export interface FontSelection {
  /** Selected font size */
  fontSize: FontSize;
  /** Scale factor (1, 2, 3, ...) */
  scale: number;
  /** Actual rendered height in cells */
  actualHeight: number;
}

/**
 * Serialized glyph: each row is a string where '#' = filled, ' ' = empty.
 * Used in JSON config for compact, human-readable font data.
 */
export type SerializedGlyph = string[];

/** Serialized font: glyphs stored as string arrays instead of boolean arrays */
export interface SerializedBitmapFont {
  width: number;
  height: number;
  glyphs: Record<string, SerializedGlyph>;
}

/** Serialized font data as it appears in the JSON config */
export type SerializedFontData = Record<FontSize, SerializedBitmapFont>;

export type HorizontalAlignment = 'left' | 'center' | 'right';
export type VerticalAlignment = 'top' | 'center' | 'bottom';

export interface TextConfig {
  /** Text to render */
  text: string;
  /** Target character height in cells */
  charHeight: number;
  /** Horizontal alignment */
  alignment: HorizontalAlignment;
  /** Vertical alignment */
  verticalAlignment: VerticalAlignment;
  /** Whether to wrap text at word boundaries */
  wordWrap: boolean;
  /** Invert mode: text becomes negative space */
  invert: boolean;
}

export interface TextGridResult {
  /** The generated boolean grid (rows × cols) */
  grid: boolean[][];
  /** Characters in the text that have no glyph definition */
  unsupportedChars: string[];
  /** Total number of lines in the text (including wrapped) */
  totalLines: number;
  /** Number of lines actually visible in the grid */
  visibleLines: number;
  /** True if grid is too small for minimum font (height < 5) */
  gridTooSmall: boolean;
}

// Font Serialization (for JSON config)

/**
 * Parses serialized font data from a JSON config into runtime FontData.
 * Converts string-based glyphs ('#' = true, ' ' = false) to boolean[][].
 */
export function parseFonts(serialized: SerializedFontData): FontData {
  const result: Partial<FontData> = {};
  const sizes: FontSize[] = ['3x5', '5x7', '7x9'];

  for (const size of sizes) {
    const serializedFont = serialized[size];
    const glyphs: GlyphMap = {};

    for (const [char, rows] of Object.entries(serializedFont.glyphs)) {
      glyphs[char] = rows.map(row => row.split('').map(c => c === '#'));
    }

    result[size] = {
      width: serializedFont.width,
      height: serializedFont.height,
      glyphs,
    };
  }

  return result as FontData;
}

/**
 * Serializes runtime FontData into the compact string format for JSON config.
 * Each glyph row becomes a string where true = '#', false = ' '.
 */
export function serializeFonts(fonts: FontData): SerializedFontData {
  const result: Partial<SerializedFontData> = {};
  const sizes: FontSize[] = ['3x5', '5x7', '7x9'];

  for (const size of sizes) {
    const font = fonts[size];
    const glyphs: Record<string, SerializedGlyph> = {};

    for (const [char, glyph] of Object.entries(font.glyphs)) {
      glyphs[char] = glyph.map(row => row.map(v => v ? '#' : ' ').join(''));
    }

    result[size] = {
      width: font.width,
      height: font.height,
      glyphs,
    };
  }

  return result as SerializedFontData;
}

// Font Selection Algorithm

/**
 * Selects the best font + scale combination to maximize rendered height
 * without exceeding the target height.
 *
 * Algorithm:
 * For each font (7x9, 5x7, 3x5), compute:
 *   scale = floor(targetHeight / fontHeight)
 *   actualHeight = fontHeight * scale
 * Select the font+scale combo with the largest actualHeight.
 * Tiebreak: prefer the higher-resolution (larger canonical) font.
 *
 * Returns null if targetHeight < 5 (minimum font 3x5 doesn't fit at scale 1).
 */
export function selectFont(targetHeight: number): FontSelection | null {
  if (targetHeight < 5) {
    return null;
  }

  const fontSizes: FontSize[] = ['7x9', '5x7', '3x5'];
  const fontHeights: Record<FontSize, number> = {
    '7x9': 9,
    '5x7': 7,
    '3x5': 5,
  };

  let bestSelection: FontSelection | null = null;

  for (const fontSize of fontSizes) {
    const fontHeight = fontHeights[fontSize];
    const scale = Math.floor(targetHeight / fontHeight);

    if (scale >= 1) {
      const actualHeight = fontHeight * scale;

      // Better if: larger actualHeight, or same actualHeight with higher-resolution font.
      // Since we iterate from highest resolution to lowest, we use > (strict) for tiebreak.
      if (bestSelection === null || actualHeight > bestSelection.actualHeight) {
        bestSelection = { fontSize, scale, actualHeight };
      }
    }
  }

  return bestSelection;
}

// Core Implementation

function createEmptyGrid(cols: number, rows: number): boolean[][] {
  const grid: boolean[][] = [];
  for (let y = 0; y < rows; y++) {
    grid.push(new Array(cols).fill(false));
  }
  return grid;
}

function createFilledGrid(cols: number, rows: number): boolean[][] {
  const grid: boolean[][] = [];
  for (let y = 0; y < rows; y++) {
    grid.push(new Array(cols).fill(true));
  }
  return grid;
}

function renderGlyph(
  grid: boolean[][],
  glyph: boolean[][],
  startX: number,
  startY: number,
  scale: number,
  invert: boolean
): void {
  const rows = grid.length;
  const cols = grid[0]?.length ?? 0;

  for (let gy = 0; gy < glyph.length; gy++) {
    for (let gx = 0; gx < glyph[gy].length; gx++) {
      const pixelOn = glyph[gy][gx];
      const cellValue = invert ? !pixelOn : pixelOn;

      for (let sy = 0; sy < scale; sy++) {
        for (let sx = 0; sx < scale; sx++) {
          const cellX = startX + gx * scale + sx;
          const cellY = startY + gy * scale + sy;

          if (cellX >= 0 && cellX < cols && cellY >= 0 && cellY < rows) {
            grid[cellY][cellX] = cellValue;
          }
        }
      }
    }
  }
}

/**
 * Checks if a character is supported by the given fonts.
 */
function isCharSupported(char: string, fonts: FontData): boolean {
  return char.toUpperCase() in fonts['3x5'].glyphs;
}

/**
 * Calculates the pixel width of a line of text.
 */
function calculateLineWidth(
  line: string,
  font: BitmapFont,
  scale: number,
  fonts: FontData
): number {
  const charSpacing = 1 * scale;
  const glyphWidth = font.width * scale;

  let width = 0;
  let charCount = 0;

  for (const char of line.toUpperCase()) {
    if (!isCharSupported(char, fonts)) continue;
    if (charCount > 0) {
      width += charSpacing;
    }
    width += glyphWidth;
    charCount++;
  }

  return width;
}

/**
 * Generates a boolean[][] grid from text configuration.
 *
 * @param config Text configuration
 * @param cols Number of columns in the output grid
 * @param rows Number of rows in the output grid
 * @param fonts Font data (from parseFonts() or directly from BitmapFont definitions)
 * @returns TextGridResult with grid and validation metadata
 */
export function generateTextGrid(
  config: TextConfig,
  cols: number,
  rows: number,
  fonts: FontData
): TextGridResult {
  const { text, charHeight, alignment, verticalAlignment, wordWrap, invert } = config;

  // Track unsupported characters
  const unsupportedChars: string[] = [];
  const upperText = text.toUpperCase();
  for (const char of upperText) {
    if (char !== '\n' && !isCharSupported(char, fonts) && !unsupportedChars.includes(char)) {
      unsupportedChars.push(char);
    }
  }

  // Select font based on target character height
  const fontSelection = selectFont(charHeight);

  // If grid is too small for any font
  if (fontSelection === null) {
    const grid = invert ? createFilledGrid(cols, rows) : createEmptyGrid(cols, rows);
    return {
      grid,
      unsupportedChars,
      totalLines: 0,
      visibleLines: 0,
      gridTooSmall: true,
    };
  }

  const { fontSize, scale } = fontSelection;
  const font = fonts[fontSize];
  const glyphWidth = font.width * scale;
  const glyphHeight = font.height * scale;
  const charSpacing = 1 * scale;
  const lineSpacing = 2 * scale;

  // Handle empty text or all-space text
  const trimmedText = text.trim();
  if (trimmedText === '') {
    const grid = invert ? createFilledGrid(cols, rows) : createEmptyGrid(cols, rows);
    return {
      grid,
      unsupportedChars: [],
      totalLines: 0,
      visibleLines: 0,
      gridTooSmall: false,
    };
  }

  // Split text into lines (handle explicit newlines)
  const rawLines = text.split('\n');

  // Process lines: word wrap if enabled, otherwise truncate at character boundary
  const processedLines: string[] = [];

  for (const rawLine of rawLines) {
    if (wordWrap) {
      const words = rawLine.split(' ');
      let currentLine = '';

      for (const word of words) {
        const testLine = currentLine === '' ? word : `${currentLine} ${word}`;
        const testWidth = calculateLineWidth(testLine, font, scale, fonts);

        if (testWidth <= cols) {
          currentLine = testLine;
        } else {
          if (currentLine !== '') {
            processedLines.push(currentLine);
          }

          const wordWidth = calculateLineWidth(word, font, scale, fonts);
          if (wordWidth <= cols) {
            currentLine = word;
          } else {
            let truncatedWord = '';
            for (const char of word) {
              const newWord = truncatedWord + char;
              const newWidth = calculateLineWidth(newWord, font, scale, fonts);
              if (newWidth <= cols) {
                truncatedWord = newWord;
              } else {
                break;
              }
            }
            processedLines.push(truncatedWord);
            currentLine = '';
          }
        }
      }

      if (currentLine !== '') {
        processedLines.push(currentLine);
      } else if (rawLine === '') {
        processedLines.push('');
      }
    } else {
      let truncatedLine = '';
      for (const char of rawLine) {
        const testLine = truncatedLine + char;
        const testWidth = calculateLineWidth(testLine, font, scale, fonts);
        if (testWidth <= cols) {
          truncatedLine = testLine;
        } else {
          break;
        }
      }
      processedLines.push(truncatedLine);
    }
  }

  const totalLines = processedLines.length;

  const calculateBlockHeight = (lineCount: number): number => {
    if (lineCount === 0) return 0;
    return lineCount * glyphHeight + (lineCount - 1) * lineSpacing;
  };

  let visibleLines = 0;
  for (let i = 1; i <= totalLines; i++) {
    if (calculateBlockHeight(i) <= rows) {
      visibleLines = i;
    } else {
      break;
    }
  }

  const grid = invert ? createFilledGrid(cols, rows) : createEmptyGrid(cols, rows);

  if (visibleLines === 0) {
    return {
      grid,
      unsupportedChars,
      totalLines,
      visibleLines: 0,
      gridTooSmall: false,
    };
  }

  const blockHeight = calculateBlockHeight(visibleLines);
  let startY: number;
  switch (verticalAlignment) {
    case 'top':
      startY = 0;
      break;
    case 'center':
      startY = Math.floor((rows - blockHeight) / 2);
      break;
    case 'bottom':
      startY = rows - blockHeight;
      break;
  }

  const linesToRender = processedLines.slice(0, visibleLines);

  for (let lineIndex = 0; lineIndex < linesToRender.length; lineIndex++) {
    const line = linesToRender[lineIndex];
    const lineWidth = calculateLineWidth(line, font, scale, fonts);

    let startX: number;
    switch (alignment) {
      case 'left':
        startX = 0;
        break;
      case 'center':
        startX = Math.floor((cols - lineWidth) / 2);
        break;
      case 'right':
        startX = cols - lineWidth;
        break;
    }

    const lineY = startY + lineIndex * (glyphHeight + lineSpacing);

    let currentX = startX;
    for (const char of line.toUpperCase()) {
      if (!isCharSupported(char, fonts)) continue;

      const glyph = font.glyphs[char];
      if (glyph) {
        renderGlyph(grid, glyph, currentX, lineY, scale, invert);
        currentX += glyphWidth + charSpacing;
      }
    }
  }

  return {
    grid,
    unsupportedChars,
    totalLines,
    visibleLines,
    gridTooSmall: false,
  };
}

// Types

export type FillType = 'linear' | 'radial' | 'angular' | 'diamond' | 'square' | 'box';

export type SeedableParam =
  | 'threshold'
  | 'gamma'
  | 'frequency'
  | 'contrast'
  | 'directionalNeighbors'
  | 'directionDensity'
  | 'fillAmount';

export type CropDirection = 'width' | 'height';

export interface FragmentConfig {
  /** Density threshold for noise (0-1) */
  threshold: number;
  /** Gamma correction for contrast (0.1-3) */
  gamma: number;
  /** Noise frequency/detail level (0.01-0.5) */
  frequency: number;
  /** Noise contrast adjustment (0.1-3) */
  contrast: number;
  /** Base random seed (0-1) */
  seed: number;
  /** Boundary fragment extent (0-999) */
  directionalNeighbors: number;
  /** Number of boundary fragments (0-999) */
  directionDensity: number;
  /** Fill percentage (0-100) */
  fillAmount: number;
  /** Fill gradient type */
  fillType: FillType;
  /** Invert fill direction */
  invertFill: boolean;
  /** Foreground color (hex) */
  foregroundColor: string;
  /** Background color (hex) */
  backgroundColor: string;
  /** Cell size in pixels */
  cellSize: number;
  /** Canvas width in pixels */
  canvasWidth?: number;
  /** Canvas height in pixels */
  canvasHeight?: number;
  /** Which parameter to vary based on seed string (optional, defaults to 'frequency') */
  seedParam?: SeedableParam;
  /** Allow cropping mode - enables partial cells at edges */
  allowCropping?: boolean;
  /** Which axis to crop: 'width' crops rightmost column, 'height' crops bottom row */
  cropDirection?: CropDirection;
}

export interface GenerateFragmentSvgOptions {
  /** Any string to use as seed (e.g., principal ID, username). If omitted, uses config.seed directly. */
  seed?: string;
  /** The fragment configuration object */
  config: FragmentConfig;
}

export interface GenerateFragmentDiffSvgOptions {
  seedA: string;
  seedB: string;
  config: FragmentConfig;
}

/**
 * Options for generating a diff SVG from two full configurations.
 * Used when animation is enabled and both From and To panels have independent params.
 */
export interface GenerateFragmentDiffFromConfigsOptions {
  /** The "From" configuration (pattern shown by default) */
  fromConfig: FragmentConfig;
  /** The "To" configuration (pattern shown on hover) */
  toConfig: FragmentConfig;
  /** Optional seed string for the "From" pattern (e.g. article title). Overrides the seedParam in fromConfig. */
  fromSeed?: string;
  /** Optional seed string for the "To" pattern. Overrides the seedParam in toConfig. */
  toSeed?: string;
}

/**
 * Animation settings exported in JSON format (v2.1.0+).
 * Nested structure for forwards compatibility with future animation settings.
 */
export interface AnimationSettings {
  /** Animation duration in milliseconds (100-5000, default: 600) */
  duration: number;
}

/**
 * Complete JSON export structure from Fragment Maker.
 * Use this type when importing exported JSON files in your application.
 *
 * @example
 * ```typescript
 * import type { FragmentExport } from './generateFragmentSvg';
 *
 * const fragmentExport: FragmentExport = await fetch('/fragment-config.json').then(r => r.json());
 *
 * // Access animation duration (v2.1.0+)
 * const duration = fragmentExport.animation?.duration ?? 600;
 * ```
 */
export interface FragmentExport {
  /** Export format version (e.g., "2.2.0") */
  version: string;
  /** ISO timestamp of export */
  exportedAt: string;
  /** Main fragment configuration (the "From" pattern when animation is enabled) */
  config: FragmentConfig;
  /** Optional animation settings (v2.1.0+). Present only when animation is enabled. */
  animation?: AnimationSettings;
  /** Optional "To" configuration for animation. Present only when animation is enabled. */
  toConfig?: FragmentConfig;
  /** Font data for text rendering (v2.2.0+). Present when any state uses text. */
  fonts?: SerializedFontData;
  /** State type for the "From" state (v2.2.0+). Defaults to 'pattern' if absent. */
  fromStateType?: 'pattern' | 'text';
  /** State type for the "To" state (v2.2.0+). Defaults to 'pattern' if absent. */
  toStateType?: 'pattern' | 'text';
  /** Text configuration for the "From" state (v2.2.0+). */
  fromTextConfig?: TextConfig;
  /** Text configuration for the "To" state (v2.2.0+). */
  toTextConfig?: TextConfig;
}

// Constants

export const PARAM_RANGES: Record<SeedableParam, { min: number; max: number; step: number }> = {
  threshold: { min: 0, max: 1, step: 0.01 },
  gamma: { min: 0.1, max: 3, step: 0.1 },
  frequency: { min: 0.01, max: 0.5, step: 0.01 },
  contrast: { min: 0.1, max: 3, step: 0.1 },
  directionalNeighbors: { min: 0, max: 999, step: 1 },
  directionDensity: { min: 0, max: 999, step: 1 },
  fillAmount: { min: 0, max: 100, step: 1 },
};

// Hash Functions

/**
 * djb2 hash algorithm - converts a string to a 32-bit unsigned integer.
 */
export function djb2Hash(str: string): number {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) + hash) ^ char;
  }
  return hash >>> 0;
}

/**
 * Normalizes a djb2 hash value to a range [0, 1].
 */
export function normalizeHash(hash: number): number {
  return hash / 0xffffffff;
}

// Internal Functions

function seededRandom(seed: number, x: number, y: number): number {
  const value = Math.sin(seed * 12.9898 + x * 78.233 + y * 43.758) * 43758.5453;
  return value - Math.floor(value);
}

function calculateFillThreshold(
  x: number,
  y: number,
  fillType: FillType,
  cols: number,
  rows: number
): number {
  const centerX = cols / 2;
  const centerY = rows / 2;

  switch (fillType) {
    case 'linear':
      return (y / rows) * 100;

    case 'radial': {
      const dx = x - centerX;
      const dy = y - centerY;
      const distance = Math.sqrt(dx * dx + dy * dy);
      const maxDistance = Math.sqrt(centerX * centerX + centerY * centerY);
      return (distance / maxDistance) * 100;
    }

    case 'angular': {
      const angle = Math.atan2(y - centerY, x - centerX);
      return ((angle + Math.PI) / (2 * Math.PI)) * 100;
    }

    case 'diamond': {
      const diamondDistance = Math.abs(x - centerX) + Math.abs(y - centerY);
      const maxDiamondDistance = centerX + centerY;
      return (diamondDistance / maxDiamondDistance) * 100;
    }

    case 'square': {
      const squareDistance = Math.max(Math.abs(x - centerX), Math.abs(y - centerY));
      const maxSquareDistance = Math.max(centerX, centerY);
      return (squareDistance / maxSquareDistance) * 100;
    }

    case 'box': {
      const distToEdge = Math.min(x, y, cols - 1 - x, rows - 1 - y);
      const maxDist = (Math.min(cols, rows) - 1) / 2;
      return maxDist > 0 ? (1 - distToEdge / maxDist) * 100 : 0;
    }
  }
}

function createBoundaryFragment(
  grid: boolean[][],
  startX: number,
  startY: number,
  color: boolean,
  seedOffset: number,
  seed: number,
  directionalNeighbors: number
): void {
  if (directionalNeighbors === 0) return;

  const actualRows = grid.length;
  const actualCols = grid[0]?.length || 0;

  if (actualCols === 0 || actualRows === 0) return;

  const directionSeed = seededRandom(seed, seedOffset, 6000);
  const isHorizontal = directionSeed > 0.5;

  const signSeed = seededRandom(seed, seedOffset, 6001);
  const direction = signSeed > 0.5 ? 1 : -1;

  const sizeSeed = seededRandom(seed, seedOffset, 6002);
  const maxLength = Math.min(Math.floor(directionalNeighbors / 50) + 2, 12);
  const length = Math.floor(sizeSeed * maxLength) + 2;

  const thicknessSeed = seededRandom(seed, seedOffset, 6003);
  const thickness = thicknessSeed > 0.7 ? 2 : 1;

  if (isHorizontal) {
    for (let i = 0; i < length; i++) {
      const x = startX + i * direction;
      if (x >= 0 && x < actualCols) {
        for (let t = 0; t < thickness; t++) {
          const y = startY + t;
          if (y >= 0 && y < actualRows) {
            grid[y][x] = color;
          }
        }
      }
    }
  } else {
    for (let i = 0; i < length; i++) {
      const y = startY + i * direction;
      if (y >= 0 && y < actualRows) {
        for (let t = 0; t < thickness; t++) {
          const x = startX + t;
          if (x >= 0 && x < actualCols) {
            grid[y][x] = color;
          }
        }
      }
    }
  }
}

function applyDirectionalNeighbors(
  grid: boolean[][],
  seed: number,
  directionalNeighbors: number,
  directionDensity: number
): void {
  if (directionDensity === 0) return;
  if (!grid || grid.length === 0 || !grid[0] || grid[0].length === 0) return;

  const actualRows = grid.length;
  const actualCols = grid[0].length;
  const boundaryCells: { x: number; y: number; color: boolean }[] = [];

  for (let y = 0; y < actualRows; y++) {
    for (let x = 0; x < actualCols; x++) {
      const currentColor = grid[y][x];
      const neighbors = [
        { x: x - 1, y },
        { x: x + 1, y },
        { x, y: y - 1 },
        { x, y: y + 1 },
      ];

      const isBoundary = neighbors.some(
        (n) =>
          n.x >= 0 &&
          n.x < actualCols &&
          n.y >= 0 &&
          n.y < actualRows &&
          grid[n.y][n.x] !== currentColor
      );

      if (isBoundary) {
        boundaryCells.push({ x, y, color: currentColor });
      }
    }
  }

  const numFragments = Math.min(directionDensity, boundaryCells.length);
  for (let i = 0; i < numFragments; i++) {
    const randomSeed = seededRandom(seed, i, 5000);
    const index = Math.floor(randomSeed * boundaryCells.length);
    const cell = boundaryCells[index];
    createBoundaryFragment(grid, cell.x, cell.y, cell.color, i, seed, directionalNeighbors);
  }
}

// Exported Internal Functions (for tool use)

/**
 * @internal Generates a 2D boolean grid. Exported for tool use only.
 */
export function generateGrid(
  cols: number,
  rows: number,
  seed: number,
  threshold: number,
  gamma: number,
  frequency: number,
  contrast: number,
  fillAmount: number,
  fillType: FillType,
  invertFill: boolean,
  directionalNeighbors: number,
  directionDensity: number
): boolean[][] {
  const grid: boolean[][] = [];

  for (let y = 0; y < rows; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < cols; x++) {
      let noise = seededRandom(seed, x * frequency, y * frequency);
      noise = Math.pow(noise, gamma);
      noise = (noise - 0.5) * contrast + 0.5;
      noise = Math.max(0, Math.min(1, noise));

      const fillThreshold = calculateFillThreshold(x, y, fillType, cols, rows);
      const effectiveFillAmount = invertFill ? 100 - fillAmount : fillAmount;
      const shouldFill = invertFill
        ? fillThreshold > effectiveFillAmount
        : fillThreshold <= effectiveFillAmount;

      row.push(shouldFill && noise > threshold);
    }
    grid.push(row);
  }

  applyDirectionalNeighbors(grid, seed, directionalNeighbors, directionDensity);
  return grid;
}

export interface GridToSvgOptions {
  allowCropping?: boolean;
  cropDirection?: CropDirection;
}

/**
 * @internal Converts a boolean grid to SVG. Exported for tool use only.
 */
export function gridToSvg(
  grid: boolean[][],
  cols: number,
  rows: number,
  cellSize: number,
  width: number,
  foregroundColor: string,
  backgroundColor: string,
  height: number,
  options?: GridToSvgOptions
): string {
  const outputWidth = width;
  const outputHeight = height;
  const { allowCropping = false, cropDirection = 'height' } = options ?? {};

  // viewBox is always the exact canvas dimensions (not grid * cellSize)
  // This ensures the SVG output matches the user's specified dimensions
  const viewBoxWidth = outputWidth;
  const viewBoxHeight = outputHeight;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${outputWidth}" height="${outputHeight}" viewBox="0 0 ${viewBoxWidth} ${viewBoxHeight}" shape-rendering="crispEdges">`;

  // Background rect to fill the entire canvas
  svg += `<rect x="0" y="0" width="${viewBoxWidth}" height="${viewBoxHeight}" fill="${backgroundColor}"/>`;

  // Render cells - with cropping, the last row/column may be partial
  for (let y = 0; y < Math.min(rows, grid.length); y++) {
    for (let x = 0; x < Math.min(cols, grid[y]?.length || 0); x++) {
      // Only render foreground cells (background is already filled)
      if (!grid[y][x]) continue;

      let rectWidth = cellSize;
      let rectHeight = cellSize;

      if (allowCropping) {
        // Calculate partial cell dimensions at edges
        if (cropDirection === 'width' && x === cols - 1) {
          // Last column may be narrower
          const remainingWidth = outputWidth - x * cellSize;
          rectWidth = Math.min(cellSize, remainingWidth);
        }
        if (cropDirection === 'height' && y === rows - 1) {
          // Last row may be shorter
          const remainingHeight = outputHeight - y * cellSize;
          rectHeight = Math.min(cellSize, remainingHeight);
        }
      }

      // Skip cells that would be completely outside the canvas
      if (rectWidth <= 0 || rectHeight <= 0) continue;

      svg += `<rect x="${x * cellSize}" y="${y * cellSize}" width="${rectWidth}" height="${rectHeight}" fill="${foregroundColor}"/>`;
    }
  }

  svg += '</svg>';
  return svg;
}

// Shared Helpers

interface Dimensions {
  cols: number;
  rows: number;
  width: number;
  height: number;
}

function computeDimensions(config: {
  cellSize: number;
  canvasWidth?: number;
  canvasHeight?: number;
  allowCropping?: boolean;
  cropDirection?: CropDirection;
}): Dimensions {
  const {
    cellSize,
    canvasWidth = 1056,
    canvasHeight = 1056,
    allowCropping = false,
    cropDirection = 'height',
  } = config;

  const width = canvasWidth;
  const height = canvasHeight;

  let cols: number;
  let rows: number;
  if (allowCropping) {
    if (cropDirection === 'width') {
      cols = Math.ceil(width / cellSize);
      rows = Math.floor(height / cellSize);
    } else {
      cols = Math.floor(width / cellSize);
      rows = Math.ceil(height / cellSize);
    }
  } else {
    cols = Math.floor(width / cellSize);
    rows = Math.floor(height / cellSize);
  }

  return { cols, rows, width, height };
}

function applySeededParam(
  config: Omit<FragmentConfig, 'seedParam'>,
  seedString: string,
  seedParam: SeedableParam
): Omit<FragmentConfig, 'seedParam'> {
  const hash = djb2Hash(seedString);
  const normalizedHash = normalizeHash(hash);
  const paramRange = PARAM_RANGES[seedParam];
  const seededValue = paramRange.min + normalizedHash * (paramRange.max - paramRange.min);
  const roundedSeededValue =
    paramRange.step >= 1
      ? Math.round(seededValue)
      : Math.round(seededValue / paramRange.step) * paramRange.step;

  return { ...config, [seedParam]: roundedSeededValue };
}

function gridFromConfig(config: Omit<FragmentConfig, 'seedParam'>, dims: Dimensions): boolean[][] {
  return generateGrid(
    dims.cols, dims.rows,
    config.seed, config.threshold, config.gamma, config.frequency,
    config.contrast, config.fillAmount, config.fillType, config.invertFill,
    config.directionalNeighbors, config.directionDensity
  );
}

// Shared Rendering Pipeline

interface RenderParams {
  config: Omit<FragmentConfig, 'seedParam'>;
}

/**
 * @internal Shared dimension→grid→svg pipeline used by both generateFragmentSvg and generateFragmentSvgDirect.
 */
function renderConfigToSvg(params: RenderParams): string {
  const { config } = params;

  const dims = computeDimensions(config);
  if (dims.cols <= 0 || dims.rows <= 0) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><text x="10" y="50" fill="red">Invalid dimensions</text></svg>`;
  }

  const grid = gridFromConfig(config, dims);

  return gridToSvg(
    grid, dims.cols, dims.rows, config.cellSize, dims.width,
    config.foregroundColor, config.backgroundColor, dims.height,
    { allowCropping: config.allowCropping, cropDirection: config.cropDirection }
  );
}

// Main Exported Functions

/**
 * Generates a Fragment pattern SVG with explicit parameter values (no seed string).
 * Used by the tool's grid preview. Shares the same rendering pipeline as generateFragmentSvg.
 *
 * @param config - The fragment configuration object
 * @returns SVG string
 */
export function generateFragmentSvgDirect(config: Omit<FragmentConfig, 'seedParam'>): string {
  return renderConfigToSvg({ config });
}

/**
 * Generates a Fragment pattern SVG from a seed string and configuration.
 *
 * The seed string is hashed using djb2 to produce a deterministic value
 * that modifies one parameter (specified by config.seedParam, defaults to 'frequency').
 *
 * @param options - Generation options
 * @param options.seed - Any string to use as seed (e.g., principal ID, username)
 * @param options.config - The fragment configuration object
 * @returns SVG string
 */
export function generateFragmentSvg(options: GenerateFragmentSvgOptions): string {
  const { seed: seedString, config } = options;
  const { seedParam = 'frequency', ...rest } = config;

  if (seedString === undefined) {
    return renderConfigToSvg({ config: rest });
  }

  const seededConfig = applySeededParam(rest, seedString, seedParam);
  return renderConfigToSvg({ config: seededConfig });
}

/**
 * Generates a single diff SVG from two seed strings.
 * Cells shared by both patterns are static. Cells unique to pattern A get data-g="a" (visible, animate off).
 * Cells unique to pattern B get data-g="b" (hidden, animate on).
 */
export function generateFragmentDiffSvg(options: GenerateFragmentDiffSvgOptions): string {
  const { seedA, seedB, config } = options;
  const { seedParam = 'frequency', ...rest } = config;

  const dims = computeDimensions(rest);
  if (dims.cols <= 0 || dims.rows <= 0) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><text x="10" y="50" fill="red">Invalid dimensions</text></svg>`;
  }

  const configA = applySeededParam(rest, seedA, seedParam);
  const configB = applySeededParam(rest, seedB, seedParam);

  const gridA = gridFromConfig(configA, dims);
  const gridB = gridFromConfig(configB, dims);

  const { cols, rows, width, height } = dims;
  const { cellSize, foregroundColor, backgroundColor, allowCropping = false, cropDirection = 'height' } = rest;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges">`;
  svg += `<rect x="0" y="0" width="${width}" height="${height}" fill="${backgroundColor}"/>`;

  for (let y = 0; y < Math.min(rows, gridA.length); y++) {
    for (let x = 0; x < Math.min(cols, gridA[y]?.length || 0); x++) {
      const inA = gridA[y][x];
      const inB = gridB[y][x];
      if (!inA && !inB) continue;

      let rectWidth = cellSize;
      let rectHeight = cellSize;

      if (allowCropping) {
        if (cropDirection === 'width' && x === cols - 1) {
          rectWidth = Math.min(cellSize, width - x * cellSize);
        }
        if (cropDirection === 'height' && y === rows - 1) {
          rectHeight = Math.min(cellSize, height - y * cellSize);
        }
      }
      if (rectWidth <= 0 || rectHeight <= 0) continue;

      const pos = `x="${x * cellSize}" y="${y * cellSize}" width="${rectWidth}" height="${rectHeight}" fill="${foregroundColor}"`;

      if (inA && inB) {
        svg += `<rect ${pos}/>`;
      } else if (inA) {
        svg += `<rect ${pos} data-g="a"/>`;
      } else {
        svg += `<rect ${pos} data-g="b" style="opacity:0"/>`;
      }
    }
  }

  svg += '</svg>';
  return svg;
}

/**
 * Options for generating a diff SVG from raw boolean grids.
 * Used when grids come from different sources (pattern generator, text generator, etc.)
 */
export interface GenerateDiffFromGridsOptions {
  /** The "From" grid (pattern shown by default) */
  gridFrom: boolean[][];
  /** The "To" grid (pattern shown on hover) */
  gridTo: boolean[][];
  /** Grid columns */
  cols: number;
  /** Grid rows */
  rows: number;
  /** Cell size in pixels */
  cellSize: number;
  /** Canvas width in pixels */
  width: number;
  /** Canvas height in pixels */
  height: number;
  /** Foreground color (hex) */
  foregroundColor: string;
  /** Background color (hex) */
  backgroundColor: string;
  /** Allow cropping mode */
  allowCropping?: boolean;
  /** Which axis to crop */
  cropDirection?: CropDirection;
}

/**
 * Generates a diff SVG from two pre-computed boolean grids.
 * Grid-agnostic: works with pattern grids, text grids, or any boolean[][] source.
 *
 * Cells shared by both grids are static. Cells unique to From get data-g="a" (visible, animate off).
 * Cells unique to To get data-g="b" (hidden, animate on).
 */
export function generateDiffFromGrids(options: GenerateDiffFromGridsOptions): string {
  const {
    gridFrom,
    gridTo,
    cols,
    rows,
    cellSize,
    width,
    height,
    foregroundColor,
    backgroundColor,
    allowCropping = false,
    cropDirection = 'height',
  } = options;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges">`;
  svg += `<rect x="0" y="0" width="${width}" height="${height}" fill="${backgroundColor}"/>`;

  for (let y = 0; y < Math.min(rows, gridFrom.length, gridTo.length); y++) {
    for (let x = 0; x < Math.min(cols, gridFrom[y]?.length || 0, gridTo[y]?.length || 0); x++) {
      const inFrom = gridFrom[y][x];
      const inTo = gridTo[y][x];
      if (!inFrom && !inTo) continue;

      let rectWidth = cellSize;
      let rectHeight = cellSize;

      if (allowCropping) {
        if (cropDirection === 'width' && x === cols - 1) {
          rectWidth = Math.min(cellSize, width - x * cellSize);
        }
        if (cropDirection === 'height' && y === rows - 1) {
          rectHeight = Math.min(cellSize, height - y * cellSize);
        }
      }
      if (rectWidth <= 0 || rectHeight <= 0) continue;

      const pos = `x="${x * cellSize}" y="${y * cellSize}" width="${rectWidth}" height="${rectHeight}" fill="${foregroundColor}"`;

      if (inFrom && inTo) {
        svg += `<rect ${pos}/>`;
      } else if (inFrom) {
        svg += `<rect ${pos} data-g="a"/>`;
      } else {
        svg += `<rect ${pos} data-g="b" style="opacity:0"/>`;
      }
    }
  }

  svg += '</svg>';
  return svg;
}

/**
 * Generates a diff SVG from two full configuration objects.
 * Used when the From and To panels have independently configured generator params.
 *
 * The fromConfig provides the base pattern (shown by default).
 * The toConfig provides the target pattern (shown on hover).
 * Colors and canvas settings are taken from fromConfig (these are shared settings).
 *
 * Cells shared by both patterns are static. Cells unique to From get data-g="a" (visible, animate off).
 * Cells unique to To get data-g="b" (hidden, animate on).
 */
export function generateFragmentDiffFromConfigs(options: GenerateFragmentDiffFromConfigsOptions): string {
  const { fromSeed, toSeed } = options;
  const { seedParam: fromSeedParam = 'frequency', ...fromRest } = options.fromConfig;
  const { seedParam: toSeedParam = 'frequency', ...toRest } = options.toConfig;

  const fromConfig = fromSeed ? applySeededParam(fromRest, fromSeed, fromSeedParam) : fromRest;
  const toConfig = toSeed ? applySeededParam(toRest, toSeed, toSeedParam) : toRest;

  // Use fromConfig for canvas/color settings (shared)
  const dims = computeDimensions(fromConfig);
  if (dims.cols <= 0 || dims.rows <= 0) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><text x="10" y="50" fill="red">Invalid dimensions</text></svg>`;
  }

  const gridFrom = gridFromConfig(fromConfig, dims);
  const gridTo = gridFromConfig(toConfig, dims);

  const { cols, rows, width, height } = dims;
  const { cellSize, foregroundColor, backgroundColor, allowCropping = false, cropDirection = 'height' } = fromConfig;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" shape-rendering="crispEdges">`;
  svg += `<rect x="0" y="0" width="${width}" height="${height}" fill="${backgroundColor}"/>`;

  for (let y = 0; y < Math.min(rows, gridFrom.length); y++) {
    for (let x = 0; x < Math.min(cols, gridFrom[y]?.length || 0); x++) {
      const inFrom = gridFrom[y][x];
      const inTo = gridTo[y][x];
      if (!inFrom && !inTo) continue;

      let rectWidth = cellSize;
      let rectHeight = cellSize;

      if (allowCropping) {
        if (cropDirection === 'width' && x === cols - 1) {
          rectWidth = Math.min(cellSize, width - x * cellSize);
        }
        if (cropDirection === 'height' && y === rows - 1) {
          rectHeight = Math.min(cellSize, height - y * cellSize);
        }
      }
      if (rectWidth <= 0 || rectHeight <= 0) continue;

      const pos = `x="${x * cellSize}" y="${y * cellSize}" width="${rectWidth}" height="${rectHeight}" fill="${foregroundColor}"`;

      if (inFrom && inTo) {
        svg += `<rect ${pos}/>`;
      } else if (inFrom) {
        svg += `<rect ${pos} data-g="a"/>`;
      } else {
        svg += `<rect ${pos} data-g="b" style="opacity:0"/>`;
      }
    }
  }

  svg += '</svg>';
  return svg;
}

// High-Level API (accepts full export JSON)

/**
 * Generates a static SVG from an exported Fragment Maker JSON config.
 * Handles both pattern and text states automatically — the consumer
 * does not need to know which state type the config uses.
 *
 * @param exportData - The full JSON export from Fragment Maker
 * @param options.seed - Optional seed string for per-item variation (pattern states only)
 * @param options.text - Optional text override (text states only). Replaces textConfig.text at render time.
 * @returns SVG string
 *
 * @example
 * ```typescript
 * const exportData = await fetch('/fragment-config.json').then(r => r.json());
 * document.getElementById('hero').innerHTML = generateSvgFromExport(exportData);
 * ```
 */
export function generateSvgFromExport(
  exportData: FragmentExport,
  options?: { seed?: string; text?: string }
): string {
  const { config, fromStateType, fromTextConfig, fonts } = exportData;

  if (fromStateType === 'text' && fromTextConfig && fonts) {
    const dims = computeDimensions(config);
    const parsedFonts = parseFonts(fonts);
    const effectiveTextConfig = options?.text !== undefined
      ? { ...fromTextConfig, text: options.text }
      : fromTextConfig;
    const { grid } = generateTextGrid(effectiveTextConfig, dims.cols, dims.rows, parsedFonts);
    return gridToSvg(
      grid, dims.cols, dims.rows,
      config.cellSize, dims.width,
      config.foregroundColor, config.backgroundColor,
      dims.height,
      { allowCropping: config.allowCropping, cropDirection: config.cropDirection }
    );
  }

  return generateFragmentSvg({ config, seed: options?.seed });
}

/**
 * Generates an animated diff SVG from an exported Fragment Maker JSON config.
 * Handles all four state type combinations (pattern↔pattern, text↔pattern,
 * pattern↔text, text↔text) automatically.
 *
 * Returns an SVG with `data-g="a"` and `data-g="b"` attributes for animation.
 * Use with `useFragmentReveal` for React, or manipulate the rects directly.
 *
 * @param exportData - The full JSON export from Fragment Maker (must have animation enabled)
 * @param options.fromSeed - Optional seed for the "from" pattern (pattern states only)
 * @param options.toSeed - Optional seed for the "to" pattern (pattern states only)
 * @param options.fromText - Optional text override for the "from" state (text states only)
 * @param options.toText - Optional text override for the "to" state (text states only)
 * @returns SVG string, or empty string if animation is not enabled
 *
 * @example
 * ```typescript
 * const exportData = await fetch('/fragment-config.json').then(r => r.json());
 * const svg = generateDiffSvgFromExport(exportData);
 * container.innerHTML = svg;
 * ```
 */
export function generateDiffSvgFromExport(
  exportData: FragmentExport,
  options?: { fromSeed?: string; toSeed?: string; fromText?: string; toText?: string }
): string {
  const { config, toConfig, fonts, fromStateType, toStateType, fromTextConfig, toTextConfig } = exportData;

  if (!toConfig && !(toStateType === 'text' && toTextConfig)) return '';

  const fromIsText = fromStateType === 'text';
  const toIsText = toStateType === 'text';

  // Both patterns: use the optimized config-based path
  if (!fromIsText && !toIsText && toConfig) {
    return generateFragmentDiffFromConfigs({
      fromConfig: config,
      toConfig,
      fromSeed: options?.fromSeed,
      toSeed: options?.toSeed,
    });
  }

  // At least one state is text — use grid-based approach
  const dims = computeDimensions(config);
  if (dims.cols <= 0 || dims.rows <= 0) return '';

  let gridFrom: boolean[][];
  let gridTo: boolean[][];

  if (fromIsText && fromTextConfig && fonts) {
    const parsedFonts = parseFonts(fonts);
    const effectiveFromTextConfig = options?.fromText !== undefined
      ? { ...fromTextConfig, text: options.fromText }
      : fromTextConfig;
    gridFrom = generateTextGrid(effectiveFromTextConfig, dims.cols, dims.rows, parsedFonts).grid;
  } else {
    const fromConfig = options?.fromSeed
      ? applySeededParam(config, options.fromSeed, config.seedParam ?? 'frequency')
      : config;
    gridFrom = gridFromConfig(fromConfig, dims);
  }

  if (toIsText && toTextConfig && fonts) {
    const parsedFonts = parseFonts(fonts);
    const effectiveToTextConfig = options?.toText !== undefined
      ? { ...toTextConfig, text: options.toText }
      : toTextConfig;
    gridTo = generateTextGrid(effectiveToTextConfig, dims.cols, dims.rows, parsedFonts).grid;
  } else if (toConfig) {
    const resolvedToConfig = options?.toSeed
      ? applySeededParam(toConfig, options.toSeed, toConfig.seedParam ?? 'frequency')
      : toConfig;
    gridTo = gridFromConfig(resolvedToConfig, dims);
  } else {
    return '';
  }

  return generateDiffFromGrids({
    gridFrom,
    gridTo,
    cols: dims.cols,
    rows: dims.rows,
    cellSize: config.cellSize,
    width: dims.width,
    height: dims.height,
    foregroundColor: config.foregroundColor,
    backgroundColor: config.backgroundColor,
    allowCropping: config.allowCropping,
    cropDirection: config.cropDirection,
  });
}

export function useReducedMotion(): boolean {
  const [reducedMotion, setReducedMotion] = useState(() => {
    if (typeof window === 'undefined') return false;
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  });

  useEffect(() => {
    const mql = window.matchMedia('(prefers-reduced-motion: reduce)');
    const onChange = (e: MediaQueryListEvent) => setReducedMotion(e.matches);
    mql.addEventListener('change', onChange);
    return () => mql.removeEventListener('change', onChange);
  }, []);

  return reducedMotion;
}

interface CellPosition {
  x: number;        // Grid column
  y: number;        // Grid row
  rectElement: SVGRectElement;
}

interface CellWithDistance extends CellPosition {
  distance: number; // BFS distance from nearest seed
  waveGroup: number; // Animation batch index
}

interface AnimState {
  aCellsOrdered: CellWithDistance[];  // "From" cells sorted by distance
  bCellsOrdered: CellWithDistance[];  // "To" cells sorted by distance
  sharedCells: CellPosition[];        // Seed points for growth
  connectionPath: CellPosition[];     // Temporary rects for snake animation

  aMaxWave: number;                   // Cache max wave for performance
  bMaxWave: number;                   // Cache max wave for performance

  startTime: number;
  currentProgress: number;            // Track current progress (0-1) for smooth reversal
  initialProgress: number;            // Progress when current animation phase started
  currentPhase: 'connection' | 'transition' | 'complete';
  direction: 'forward' | 'backward' | 'idle';
  animFrameId: number | null;
}

// Extract grid position from SVG rect
function extractCellPositions(
  rects: SVGRectElement[],
  cellSize: number
): CellPosition[] {
  return rects.map(rect => ({
    x: Math.round(parseInt(rect.getAttribute('x') || '0') / cellSize),
    y: Math.round(parseInt(rect.getAttribute('y') || '0') / cellSize),
    rectElement: rect
  }));
}

// BFS distance calculation (4 directions only)
function calculateDistanceMap(
  gridCols: number,
  gridRows: number,
  seedCells: CellPosition[],
  targetCells: CellPosition[]
): Map<string, number> {
  const distanceMap = new Map<string, number>();
  const queue: Array<{x: number, y: number, dist: number}> = [];

  // Initialize seeds at distance 0
  seedCells.forEach(seed => {
    distanceMap.set(`${seed.x},${seed.y}`, 0);
    queue.push({x: seed.x, y: seed.y, dist: 0});
  });

  // BFS flood fill (4 directions only)
  while (queue.length > 0) {
    const current = queue.shift()!;
    const neighbors = [
      {x: current.x - 1, y: current.y},  // left
      {x: current.x + 1, y: current.y},  // right
      {x: current.x, y: current.y - 1},  // up
      {x: current.x, y: current.y + 1},  // down
    ];

    for (const neighbor of neighbors) {
      if (neighbor.x < 0 || neighbor.x >= gridCols ||
          neighbor.y < 0 || neighbor.y >= gridRows) continue;

      const key = `${neighbor.x},${neighbor.y}`;
      const isTargetCell = targetCells.some(c => c.x === neighbor.x && c.y === neighbor.y);

      if (isTargetCell && !distanceMap.has(key)) {
        const newDist = current.dist + 1;
        distanceMap.set(key, newDist);
        queue.push({...neighbor, dist: newDist});
      }
    }
  }

  return distanceMap;
}

// Group cells into animation waves with randomization for organic feel
function groupIntoWaves(
  cellsWithDistance: CellWithDistance[],
  targetFrames: number
): CellWithDistance[] {
  if (cellsWithDistance.length === 0) return [];

  // Add random tie-breaker to each cell for stable randomization
  const cellsWithTieBreaker = cellsWithDistance.map(cell => ({
    ...cell,
    tieBreaker: Math.random()
  }));

  // Sort by distance first, then by random tie-breaker for same distance
  const sorted = cellsWithTieBreaker.sort((a, b) => {
    const distDiff = a.distance - b.distance;
    if (Math.abs(distDiff) < 0.1) {
      // Same distance level - use stable tie-breaker
      return a.tieBreaker - b.tieBreaker;
    }
    return distDiff;
  });

  // Assign continuous wave values for smoother animation
  // Start from 1 instead of 0 to avoid immediate visibility at progress=0
  return sorted.map((cell, index) => ({
    ...cell,
    waveGroup: ((index + 1) / sorted.length) * targetFrames
  }));
}

// Create snake connection path (Bresenham's line)
function createConnectionPath(
  fromCell: CellPosition,
  toCell: CellPosition,
  cellSize: number,
  svg: SVGSVGElement
): CellPosition[] {
  const path: CellPosition[] = [];

  // Bresenham's line algorithm
  let x0 = fromCell.x, y0 = fromCell.y;
  const x1 = toCell.x, y1 = toCell.y;
  const dx = Math.abs(x1 - x0);
  const dy = Math.abs(y1 - y0);
  const sx = x0 < x1 ? 1 : -1;
  const sy = y0 < y1 ? 1 : -1;
  let err = dx - dy;

  while (x0 !== x1 || y0 !== y1) {
    // Create temporary rect for connection
    const rect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
    rect.setAttribute('x', String(x0 * cellSize));
    rect.setAttribute('y', String(y0 * cellSize));
    rect.setAttribute('width', String(cellSize));
    rect.setAttribute('height', String(cellSize));
    rect.setAttribute('fill', 'currentColor');
    rect.setAttribute('opacity', '0');
    rect.setAttribute('data-connection', 'true');

    svg.appendChild(rect);
    path.push({x: x0, y: y0, rectElement: rect as SVGRectElement});

    const e2 = 2 * err;
    if (e2 > -dy) { err -= dy; x0 += sx; }
    if (e2 < dx) { err += dx; y0 += sy; }
  }

  return path;
}

export function useFragmentReveal(
  containerRef: React.RefObject<HTMLDivElement | null>,
  durationMs: number = 600,
  enabled: boolean = true
) {
  const stateRef = useRef<AnimState>({
    aCellsOrdered: [],
    bCellsOrdered: [],
    sharedCells: [],
    connectionPath: [],
    aMaxWave: 0,
    bMaxWave: 0,
    startTime: 0,
    currentProgress: 0,
    initialProgress: 0,
    currentPhase: 'complete',
    direction: 'idle',
    animFrameId: null,
  });
  const reducedMotion = useReducedMotion();

  useEffect(() => {
    return () => {
      if (stateRef.current.animFrameId !== null) {
        cancelAnimationFrame(stateRef.current.animFrameId);
        stateRef.current.animFrameId = null;
      }
    };
  }, []);

  const tick = useCallback((timestamp: number) => {
    const s = stateRef.current;

    if (!s.startTime) {
      s.startTime = timestamp;
    }

    const elapsed = timestamp - s.startTime;
    let progress = Math.min(elapsed / durationMs, 1);

    // Calculate effective progress based on direction
    // Use initialProgress (set once at animation start) to avoid exponential compounding
    let effectiveProgress: number;
    if (s.direction === 'forward') {
      // Linearly interpolate from initialProgress to 1.0
      effectiveProgress = s.initialProgress + (progress * (1.0 - s.initialProgress));
      effectiveProgress = Math.min(effectiveProgress, 1.0);
    } else if (s.direction === 'backward') {
      // Linearly interpolate from initialProgress to 0.0
      effectiveProgress = s.initialProgress * (1.0 - progress);
      effectiveProgress = Math.max(effectiveProgress, 0);
    } else {
      return;
    }

    if (s.direction === 'forward') {
      // Trigger final frame slightly early (at 98% progress) to ensure smooth completion
      if (progress >= 0.98) {
        // Final frame - directly set all cells to final state, no wave calculations
        s.aCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '0');
        s.bCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '1');
        s.connectionPath.forEach(cell => cell.rectElement.remove());
        s.connectionPath = [];
        s.currentProgress = 1.0;
        s.currentPhase = 'complete';
        s.direction = 'idle';
        s.animFrameId = null;

      } else {
        // Normal frames - wave-based animation
        s.currentProgress = effectiveProgress;

        const aCurrentWave = effectiveProgress * s.aMaxWave;
        const bCurrentWave = effectiveProgress * s.bMaxWave;

        s.aCellsOrdered.forEach(cell => {
          if (cell.waveGroup <= aCurrentWave) {
            cell.rectElement.style.opacity = '0';
          } else {
            cell.rectElement.style.opacity = '';
          }
        });

        s.bCellsOrdered.forEach(cell => {
          if (cell.waveGroup <= bCurrentWave) {
            cell.rectElement.style.opacity = '1';
          } else {
            cell.rectElement.style.opacity = '0';
          }
        });

        s.animFrameId = requestAnimationFrame(tick);
      }
    } else if (s.direction === 'backward') {
      // Cleanup connection paths
      if (s.connectionPath.length > 0) {
        s.connectionPath.forEach(cell => cell.rectElement.remove());
        s.connectionPath = [];
      }

      // Trigger final frame slightly early (at 98% progress) to ensure smooth completion
      if (progress >= 0.98) {
        // Final frame - directly set all cells to initial state
        s.aCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '');
        s.bCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '0');
        s.currentProgress = 0;
        s.direction = 'idle';
        s.animFrameId = null;

      } else {
        // Normal frames - use same wave logic as forward; decreasing effectiveProgress
        // naturally reverses the animation without any visual discontinuity
        s.currentProgress = effectiveProgress;

        const aCurrentWave = effectiveProgress * s.aMaxWave;
        const bCurrentWave = effectiveProgress * s.bMaxWave;

        s.aCellsOrdered.forEach(cell => {
          if (cell.waveGroup <= aCurrentWave) {
            cell.rectElement.style.opacity = '0';
          } else {
            cell.rectElement.style.opacity = '';
          }
        });

        s.bCellsOrdered.forEach(cell => {
          if (cell.waveGroup <= bCurrentWave) {
            cell.rectElement.style.opacity = '1';
          } else {
            cell.rectElement.style.opacity = '0';
          }
        });

        s.animFrameId = requestAnimationFrame(tick);
      }
    }
  }, [durationMs]);

  const ensureRects = useCallback((): boolean => {
    const s = stateRef.current;

    // Check if rects are already initialized and connected
    if (
      (s.aCellsOrdered.length > 0 && s.aCellsOrdered[0].rectElement.isConnected) ||
      (s.bCellsOrdered.length > 0 && s.bCellsOrdered[0].rectElement.isConnected)
    ) return true;

    const container = containerRef.current;
    if (!container) return false;

    const svg = container.querySelector('svg');
    if (!svg) return false;

    // 1. Query all rect elements
    const aRects = Array.from(svg.querySelectorAll('rect[data-g="a"]')) as SVGRectElement[];
    const bRects = Array.from(svg.querySelectorAll('rect[data-g="b"]')) as SVGRectElement[];
    const sharedRects = Array.from(svg.querySelectorAll('rect:not([data-g])')) as SVGRectElement[];

    if (aRects.length === 0 && bRects.length === 0) return false;

    // 2. Extract positions (determine cellSize from first rect)
    const firstRect = aRects[0] || bRects[0] || sharedRects[0];
    if (!firstRect) return false;

    const cellSize = parseInt(firstRect.getAttribute('width') || '1');
    const viewBox = svg.getAttribute('viewBox')?.split(' ') || [];
    const gridCols = Math.round(parseInt(viewBox[2] || '1056') / cellSize);
    const gridRows = Math.round(parseInt(viewBox[3] || '1056') / cellSize);

    const aCells = extractCellPositions(aRects, cellSize);
    const bCells = extractCellPositions(bRects, cellSize);
    const sharedCells = extractCellPositions(sharedRects, cellSize);

    // 3. Determine seed points
    let seedCells = sharedCells;
    if (seedCells.length === 0 && aCells.length > 0 && bCells.length > 0) {
      // Find nearest pair for connection path
      let minDist = Infinity;
      let nearestA: CellPosition | null = null;
      let nearestB: CellPosition | null = null;

      aCells.forEach(a => {
        bCells.forEach(b => {
          const dist = Math.abs(a.x - b.x) + Math.abs(a.y - b.y);
          if (dist < minDist) {
            minDist = dist;
            nearestA = a;
            nearestB = b;
          }
        });
      });

      if (nearestA && nearestB) {
        s.connectionPath = createConnectionPath(nearestA, nearestB, cellSize, svg);
        seedCells = [nearestA, nearestB]; // Use both endpoints as seeds
      }
    }

    // 4. Calculate distances
    const aDistances = calculateDistanceMap(gridCols, gridRows, seedCells, aCells);
    const bDistances = calculateDistanceMap(gridCols, gridRows, seedCells, bCells);

    // Handle orphaned cells (unreachable by BFS)
    const maxADistance = aDistances.size > 0 ? Math.max(...Array.from(aDistances.values())) : 0;
    const maxBDistance = bDistances.size > 0 ? Math.max(...Array.from(bDistances.values())) : 0;

    // 5. Attach distances to cells
    const aCellsWithDist = aCells.map(cell => ({
      ...cell,
      distance: aDistances.get(`${cell.x},${cell.y}`) ?? (maxADistance + 1),
      waveGroup: 0
    }));

    const bCellsWithDist = bCells.map(cell => ({
      ...cell,
      distance: bDistances.get(`${cell.x},${cell.y}`) ?? (maxBDistance + 1),
      waveGroup: 0
    }));

    // 6. Group into waves
    const targetFrames = Math.max(1, Math.ceil(durationMs / 16.67));
    s.aCellsOrdered = groupIntoWaves(aCellsWithDist, targetFrames);
    s.bCellsOrdered = groupIntoWaves(bCellsWithDist, targetFrames);
    s.sharedCells = sharedCells;

    // Cache max wave values for performance
    // Multiply by 1.05 so all cells animate before effectiveProgress reaches 0.95
    s.aMaxWave = s.aCellsOrdered.length > 0
      ? Math.max(...s.aCellsOrdered.map(c => c.waveGroup)) * 1.05
      : 0;
    s.bMaxWave = s.bCellsOrdered.length > 0
      ? Math.max(...s.bCellsOrdered.map(c => c.waveGroup)) * 1.05
      : 0;

    return true;
  }, [containerRef, durationMs]);

  const onMouseEnter = useCallback(() => {
    if (!enabled) return;
    if (!ensureRects()) return;
    const s = stateRef.current;

    if (reducedMotion) {
      // Instant transition for reduced motion
      s.aCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '0');
      s.bCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '1');
      s.connectionPath.forEach(cell => cell.rectElement.remove());
      s.connectionPath = [];
      s.currentProgress = 1;
      return;
    }

    // Cancel existing animation if running
    if (s.animFrameId !== null) {
      cancelAnimationFrame(s.animFrameId);
    }

    s.initialProgress = s.currentProgress;
    s.direction = 'forward';
    s.startTime = 0;
    s.animFrameId = requestAnimationFrame(tick);
  }, [tick, reducedMotion, enabled, ensureRects]);

  const onMouseLeave = useCallback(() => {
    if (!enabled) return;
    const s = stateRef.current;
    if (s.aCellsOrdered.length === 0 && s.bCellsOrdered.length === 0) return;

    if (reducedMotion) {
      // Instant reverse for reduced motion
      s.aCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '');
      s.bCellsOrdered.forEach(cell => cell.rectElement.style.opacity = '0');
      s.connectionPath.forEach(cell => cell.rectElement.remove());
      s.connectionPath = [];
      s.currentProgress = 0;
      return;
    }

    // Cancel existing animation if running
    if (s.animFrameId !== null) {
      cancelAnimationFrame(s.animFrameId);
    }

    s.initialProgress = s.currentProgress;
    s.direction = 'backward';
    s.startTime = 0;
    s.animFrameId = requestAnimationFrame(tick);
  }, [tick, reducedMotion, enabled]);

  return { onMouseEnter, onMouseLeave };
}

/**
 * Observes a container element and returns its size snapped to the nearest
 * cell boundary. This ensures the SVG grid aligns cleanly with the container
 * without partial cells or wasted space.
 *
 * Only triggers a re-render when the size changes by at least one full cell,
 * avoiding unnecessary SVG regeneration on sub-pixel resize events.
 *
 * @param containerRef - Ref to the container element to observe
 * @param cellSize - The cell size from your FragmentConfig (e.g. `config.cellSize`)
 * @returns `{ width, height }` snapped to cell boundaries, or `null` before first measurement or if cellSize is undefined
 */
export function useFragmentSize(
  containerRef: React.RefObject<HTMLElement | null>,
  cellSize: number | undefined
): { width: number; height: number } | null {
  const [size, setSize] = useState<{ width: number; height: number } | null>(
    null
  );
  const lastSize = useRef<{ width: number; height: number } | null>(null);

  useEffect(() => {
    const el = containerRef.current;
    if (!el || cellSize === undefined) return;

    const observer = new ResizeObserver(entries => {
      const { width, height } = entries[0].contentRect;
      if (width <= 0 || height <= 0) return;

      const w = Math.ceil(width);
      const h = Math.ceil(height);
      const prev = lastSize.current;

      if (
        !prev ||
        Math.abs(w - prev.width) >= cellSize ||
        Math.abs(h - prev.height) >= cellSize
      ) {
        const snapped = { width: w, height: h };
        lastSize.current = snapped;
        setSize(snapped);
      }
    });

    observer.observe(el);
    return () => observer.disconnect();
  }, [containerRef, cellSize]);

  return size;
}
